### ISSUE TITLE
[Task] 백엔드 초기 세팅 설정(jpa, spring web, lombok, junit5)

### ISSUE THREAD

**Issue by hardy716** [MAK-E-AT/Backend#10]
#### [Description]
- 백엔드 초기 세팅을 설정합니다.

#### [Details]
- jpa 라이브러리 : ORM(Object-Relational Mapping) 구현을 손 쉽게 도와주는 라이브러리
- spring web 라이브러리 : 스프링 WEB서버 가동을 위해 필요한 라이브러리
- lombok 라이브러리 : 다수의 편리한 기능을 제공하는 라이브러리
- junit5 : 자바 테스트 코드 돌릴 때 사용되는 프레임워크

**Comment by hanjaegyeong** [comment]
## Feature Summary

백엔드 프로젝트 초기 세팅
Gradle Project, 자바17, Spring Boot 3.0.5 이용

## Dependencies

1. Spring JPA(3.0.4)
    
    자바 ORM 기술 표준 프레임워크.
    
2. Spring WEB(3.0.5)
    
    스프링 서버 가동을 위한 프레임워크.
    
3. Lombok(1.18.26)
    
    @getter, @setter, @log등의 편의 애노테이션을 가져오기 위한 라이브러리
